version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - fluentd
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ${FOLDER_FOR_CONFIGS:?err}/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitor
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:${FLUENTD_PORT_TCP:?err}"
        tag: prometheus
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    depends_on:
      - fluentd
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/node-exporter/proc:/host/proc:ro
      - ${FOLDER_FOR_CONFIGS:?err}/node-exporter/sys:/host/sys:ro
      - ${FOLDER_FOR_CONFIGS:?err}/node-exporter/:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitor
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:${FLUENTD_PORT_TCP:?err}"
        tag: node-exporter